# Generated by Django 3.2 on 2021-05-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_item_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='avaliability',
            new_name='availability',
        ),
    ]
